"""
Error codes for SMSAPI
from http://www.smsapi.pl/en/sms-api/api-error-codes
"""

error_codes = {
    '8': 'Error in request (please report)',
    '11': 'Message too long or there is no message or parameter nounicode is set and special characters (including Polish characters) are used. For VMS message the error means no WAV file or TTS content.',
    '12': 'Message has over 160 chars when parameter &single=1',
    '13': 'Invalid phone number',
    '14': 'Wrong sender name',
    '17': 'FLASH message cannot contain special characters',
    '18': 'Invalid number of parameters',
    '19': 'Too many messages in one request',
    '20': 'Invalid number of IDX parametes',
    '21': 'MMS message is too large (up to 100kB)',
    '22': 'Wrong SMIL format',
    '23': 'Error occured while loading file for MMS or VMS message',
    '24': 'Wrong file format',
    '25': 'Parameters &normalize and &datacoding musn\'t appear in the same request.',
    '26': 'MMS subject is to long. Subject may contain up to 30 characters.',
    '30': 'Wrong UDH parameter when datacoding=bin is set',
    '31': 'Error occured while TTS conversion',
    '32': 'Eco, MMS and VMS messages cannot be sent at international numbers or sending messages to non-Polish numbers has been disabled (for Pro messages).',
    '33': 'There are no correct numbers',
    '35': 'Wrong tts_lector given. Available values: agnieszka, ewa, jacek, jan, maja',
    '36': 'Sending binary messages with footer is disallowed',
    '40': 'No group with given name in phonebook',
    '41': 'Chosen group is empty',
    '50': 'Message can be scheduled up to 3 months in the future',
    '51': 'Wrong VMS sent date, VMS messages may be sent only between 8am and 10pm or combination of parameters try and interval may cause sending one of tries after 10pm.',
    '52': 'Too many attempts to send message from one number (up to 10 attempts within 60 sek. for single number)',
    '53': 'Not unique idx value.',
    '54': 'Wrong date - (only unix timestamp and ISO 8601)',
    '55': 'No landline numbers in the recipients list and paremeter skip_gsm set.',
    '56': 'The difference between date sent and expiration date can\'t be less than 1 and more tha 12 hours.',
    '60': 'Group of codes with rthis name doesn\'t exist.',
    '61': 'Group of codes are expired.',
    '62': 'All codes from this group are already used.',
    '65': 'Not enough unused codes in the group. There is fewer codes in the group that numbers in request.',
    '66': 'Parameter [%kod%] the message content is missing. This parameter is necessary for requests with parameter &discount_group.',
    '101': 'Invalid authorization data',
    '102': 'Invalid username or password',
    '103': 'Insufficient credits on user\'s account',
    '104': 'No such template',
    '105': 'Invalid IP address (for IP filter turned on)',
    '110': 'Service is not available on account (SMS, MMS, VMS or HLR).',
    '200': 'Unsuccessful attempt of sending, try again',
    '201': 'System internal error (please report)',
    '202': 'Too many simultaneous requests, message won\'t be sent (try again)',
    '300': 'Invalid value in \'points\' field (when using points field value 1 is required)',
    '301': 'Message with provided ID doesn\'t exist or is scheduled for following 60 seconds (such messages cannot be deleted)',
    '400': 'Invalid message ID of a status response',
    '999': 'System internal error (please report)',
    '1000': 'Acction available only for main user',
    '1001': 'Invalid action (expected one of following parameters: add_user, set_user, get_user, credits)',
    '1010': 'Subuser\'s adding error',
    '1020': 'Subuser\'s editing error',
    '1021': 'No data to edit, at least one parameter has to be edited',
    '1030': 'Checking user\'s data error',
    '1032': 'Subuser doesn\'t exist for this main user',
    '1100': 'Subuser\'s data error',
    '1110': 'Invalid new subuser\'s name',
    '1111': 'New subuser\'s name is missing',
    '1112': 'Too short new subuser\'s name, it has to contain minimum 3 characters',
    '1113': 'Too long new subuser\'s name, subuser\'s name with main user\'s prefix may contain maximum 32 characters',
    '1114': 'Not allowed characters occured in subuser\'s name, following are allowed: letters [A-Z], digits [0-9] and following others @, -, _ and .',
    '1115': 'Another user with the same name exists',
    '1120': 'New subuser\'s password error',
    '1121': 'Password too short',
    '1122': 'Password too long',
    '1123': 'Password should be hashed with MD5',
    '1130': 'Credit limit error',
    '1131': 'Parameter limit ought to be a number',
    '1140': 'Month limit error',
    '1141': 'Parameter month_limit ought to be a number',
    '1150': 'Wrong senders parameter vaule, binnary 0 and 1 values allowed',
    '1160': 'Wrong phonebook parameter vaule, binnary 0 and 1 values allowed',
    '1170': 'Wrong active parameter vaule, binnary 0 and 1 values allowed',
    '1180': 'Parameter info error',
    '1183': 'Parameter info is too long',
    '1190': 'API password for subuser\'s account error',
    '1192': 'Wrong API password lenght (password hashed with MD5 should have 32 chars)',
    '1193': 'API password should be hashed with MD5',
    '2001': 'Invalid action (parameter add, status, delete or list expected)',
    '2010': 'New sender name adding error',
    '2030': 'Sender name\'s status checking error',
    '2031': 'Such sender name doesn\'t exist',
    '2060': 'Default sender name error',
    '2061': 'Sender name has to be active for setting it as defaul',
    '2062': 'This sender name is already set as default',
    '2100': 'Data error',
    '2110': 'Sender name error',
    '2111': 'Sender name is missing for adding new sender name action (parameter &add is empty)',
    '2112': 'Invalid Sender Name\'s name (i.e. Name containing special chars or name too long), sender name may contain up to 11 chars, chars allowed: a-z A-Z 0-9 - . [spacebar]',
    '2115': 'Sender name already exist'
}

"""
Delivery codes
"""



